repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
  -   repo: https://github.com/psf/black
      rev: 23.10.0
      hooks:
      -   id: black
  -   repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
      -   id: flake8
          args: [--max-line-length=88]
  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v3.12.0
      hooks:
      -   id: reorder-python-imports
